# Generated by Django 2.2.16 on 2022-08-14 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное значение: 1 минута')], verbose_name='время приготовления в минутах'),
        ),
    ]
